kern: Fix undefined __noinline__ issue
When `make nocore`, there will be a compiling error:

```bash
In file included from kern/boringssl_a_13_kern.c:72:
In file included from ./kern/openssl.h:16:
./kern/tc.h:116:8: error: use of undeclared identifier '__noinline__'
static __noinline bool filter_pcap_ebpf_l2(void *_skb, void *__skb,
       ^
./kern/bpf/bpf_helpers.h:47:35: note: expanded from macro '__noinline'
                                  ^
/lib/modules/6.5.0-15-generic/build/include/linux/compiler_attributes.h:244:56: note: expanded from macro 'noinline'
                                                       ^
1 error generated.
```

This is because definition of `noinline` in `compiler_attributes.h` is
incorrect for us, which makes `__noinline` expanding to clang-unrecognised
`__attribute__((__attribute__((__noinline__))))`.

So, we have to `undef noinline` for clang compiling for `make nocore`.

Signed-off-by: Leon Hwang <hffilwlqm@gmail.com>